const state={connection:'Trifazat',power:'22 kW',board:24,items:[],next:1,drag:null};
const catalog=[
 {group:'Protecție la supracurent – circuite monofazate',items:[10,16,20,25,32].map(a=>({id:`mcb-${a}`,name:`MCB 1P+N ${a} A`,type:'MCB',modules:2,amp:a,detail:'1P+N • protecție la supracurent'}))},
 {group:'Protecție diferențială – RCCB',items:[25,40,63].map(a=>({id:`rccb-${a}`,name:`RCCB 2P ${a} A / 30 mA`,type:'RCCB',modules:2,amp:a,detail:'2P • DDR 30 mA'}))},
 {group:'Protecție diferențială + supracurent – RCBO',items:[10,16,20,25,32].map(a=>({id:`rcbo-${a}`,name:`RCBO 1P+N ${a} A / 30 mA`,type:'RCBO',modules:2,amp:a,detail:'1P+N • DDR 30 mA'}))},
 {group:'Protecție la arc electric – AFDD',items:[16,20,25,32].map(a=>({id:`afdd-${a}`,name:`AFDD 1P+N ${a} A`,type:'AFDD',modules:3,amp:a,detail:'1P+N • aparat 3 module (configurabil)'}))},
 {group:'Protecție la supratensiuni – SPD',items:[
  {id:'spd-t2-1p',name:'SPD Tip 2 • 1P+N',type:'SPD',modules:2,detail:'Tip 2 • 1P+N'},
  {id:'spd-t2-3p',name:'SPD Tip 2 • 3P+N',type:'SPD',modules:4,detail:'Tip 2 • 3P+N'},
  {id:'spd-t1-t2',name:'SPD Tip 1+2 • 3P+N',type:'SPD',modules:4,detail:'Tip 1+2 • 3P+N'},
  {id:'spd-t3',name:'SPD Tip 3 • modular',type:'SPD',modules:2,detail:'Tip 3 • alegere în funcție de aplicație'}
 ]},
 {group:'Comandă și protecții speciale',items:[
  {id:'contactor-2p',name:'Contactor 2P',type:'CONTACTOR',modules:2,detail:'2P • comandă'},
  {id:'contactor-4p',name:'Contactor 4P',type:'CONTACTOR',modules:4,detail:'4P • comandă'},
  {id:'relay-voltage',name:'Releu monitorizare tensiune',type:'RELEU',modules:2,detail:'monitorizare • necesită coordonare'}
 ]}
];
const fixed=[{id:'general',name:'GENERAL',modules:2,fixed:true},{id:'spd-fixed',name:'SPD',modules:2,fixed:true}];
const all=()=>catalog.flatMap(g=>g.items);
function icon(item){const labels={MCB:'MCB',RCCB:'RCCB',RCBO:'RCBO',AFDD:'AFDD',SPD:'SPD',CONTACTOR:'K',RELEU:'R'};const l=labels[item.type]||'?';const sub=item.amp?item.amp+'A':'';return `<svg viewBox="0 0 80 100" xmlns="http://www.w3.org/2000/svg"><rect x="12" y="5" width="56" height="90" rx="4" fill="#f7f7f5" stroke="#8e9498"/><rect x="18" y="12" width="44" height="18" rx="2" fill="#e2e5e6"/><text x="40" y="25" text-anchor="middle" font-size="9" font-family="Arial" font-weight="700" fill="#20262b">${l}</text><rect x="27" y="37" width="26" height="35" rx="3" fill="#d8dcde" stroke="#8e9498"/><rect x="35" y="43" width="10" height="22" rx="2" fill="#555b60"/><text x="40" y="84" text-anchor="middle" font-size="8" font-family="Arial" font-weight="700" fill="#20262b">${sub}</text></svg>`}
function boardInfo(){document.getElementById('boardInfo').textContent=`${state.connection} • ${state.power} • ${state.board} module • 12 module/șină`}
function occ(){let used=4+state.items.reduce((s,x)=>s+x.modules,0), total=state.board, pct=Math.round(used/total*100);document.getElementById('occupancy').textContent=`Ocupare: ${used}/${total} module (${pct}%)`;return {used,total,pct}}
function render(){boardInfo();renderRails();renderCatalog();occ()}
function renderRails(){const el=document.getElementById('rails');el.innerHTML='';const rows=state.board/12;for(let r=0;r<rows;r++){const rail=document.createElement('div');rail.className='rail';rail.dataset.row=r;for(let s=0;s<12;s++){const slot=document.createElement('div');slot.className='slot';slot.dataset.row=r;slot.dataset.slot=s;slot.addEventListener('dragover',e=>e.preventDefault());slot.addEventListener('drop',e=>{e.preventDefault();if(state.drag)moveItem(state.drag,r,s)});rail.appendChild(slot)}el.appendChild(rail)}
 const placed=[...fixed.map((x,i)=>({...x,row:0,slot:i*2})),...state.items];placed.forEach(x=>{const row=el.children[x.row], start=row?.children[x.slot];if(!start)return;const d=document.createElement('div');d.className='device'+(x.fixed?' fixed':'');d.style.left=`calc(${x.slot/12*100}% + 2px)`;d.style.width=`calc(${x.modules/12*100}% - 4px)`;d.innerHTML=icon(x);d.title=x.name;if(!x.fixed){d.draggable=true;d.dataset.uid=x.uid;d.addEventListener('dragstart',()=>state.drag=x.uid);d.addEventListener('dragend',()=>state.drag=null);d.addEventListener('click',()=>openModal(x.uid))}start.appendChild(d)})}
function findByUid(uid){return state.items.find(x=>x.uid===uid)}
function occupied(exclude){const map=Array.from({length:state.board/12},()=>Array(12).fill(false));fixed.forEach(x=>{for(let i=0;i<x.modules;i++)map[0][i]=true});state.items.forEach(x=>{if(x.uid===exclude)return;for(let i=0;i<x.modules;i++)map[x.row][x.slot+i]=true});return map}
function fits(row,slot,mods,exclude){if(row<0||row>=state.board/12||slot<0||slot+mods>12)return false;const m=occupied(exclude);for(let i=0;i<mods;i++)if(m[row][slot+i])return false;return true}
function firstFit(mods){for(let r=0;r<state.board/12;r++)for(let s=0;s<=12-mods;s++)if(fits(r,s,mods))return {row:r,slot:s};return null}
function addItem(id){const p=all().find(x=>x.id===id), pos=firstFit(p.modules);if(!pos){showError(`Nu există ${p.modules} module libere pe șinele DIN.`);return}state.items.push({...p,uid:'u'+state.next++,...pos});clearError();render()}
function moveItem(uid,row,slot){const x=findByUid(uid);if(!x)return;if(fits(row,slot,x.modules,uid)){x.row=row;x.slot=slot;clearError();render()}else showError(`Aparatul ${x.name} nu încape în poziția aleasă sau intră peste alt aparat.`)}
function change(uid,id){const x=findByUid(uid),p=all().find(y=>y.id===id),old={...x};if(fits(x.row,x.slot,p.modules,uid)){Object.assign(x,p,{uid,row:old.row,slot:old.slot});clearError();closeModal();render();return}const pos=firstFit(p.modules);if(pos){Object.assign(x,p,pos);clearError();closeModal();render()}else{closeModal();showError(`Aparatul ales (${p.modules} module) nu încape pe șine. S-a păstrat varianta anterioară.`)}}
function openModal(uid){const x=findByUid(uid), body=document.getElementById('modalBody');body.innerHTML=`<p><b>Poziție:</b> șina ${x.row+1}, modul ${x.slot+1} • <b>actual:</b> ${x.name}</p><div class="choices">${all().map(p=>`<div class="choice"><span><b>${p.name}</b><br><small>${p.detail} • ${p.modules} module</small></span><button data-id="${p.id}">Alege</button></div>`).join('')}</div><button class="add" id="deleteBtn">Șterge aparatul</button>`;body.querySelectorAll('.choice button').forEach(b=>b.onclick=()=>change(uid,b.dataset.id));document.getElementById('deleteBtn').onclick=()=>{state.items=state.items.filter(z=>z.uid!==uid);closeModal();clearError();render()};document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function showError(msg){const a=document.getElementById('alert');a.className='alert error';a.textContent=msg;setTimeout(()=>{a.className='alert';a.textContent=''},6500)}function clearError(){const a=document.getElementById('alert');a.className='alert ok';a.textContent='Configurație validă pentru ocuparea fizică a șinelor';setTimeout(()=>{a.className='alert';a.textContent=''},1800)}
function renderCatalog(){const c=document.getElementById('catalog');c.innerHTML='';catalog.forEach((g,i)=>{const d=document.createElement('details');d.className='group';d.open=i===0;d.innerHTML=`<summary>${g.group}</summary><div class="items"></div>`;const box=d.querySelector('.items');g.items.forEach(p=>{const card=document.createElement('div');card.className='card';card.innerHTML=`<div class="icon">${icon(p)}</div><div><div class="name">${p.name}</div><div class="meta">${p.detail} • ${p.modules} module</div><button class="add">＋ Adaugă pe șină</button></div>`;card.querySelector('.add').onclick=()=>addItem(p.id);box.appendChild(card)});c.appendChild(d)})}
document.getElementById('closeModal').onclick=closeModal;document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});render();
